version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.0
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv demo
            . demo/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . demo/bin/activate
            python test_demo.py
      - run:
          name: Build and push Docker image
          command: |
            . demo/bin/activate
            pyinstaller -f demo.py
            docker build -t premvilas30/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push premvilas30/$IMAGE_NAME:$TAG
