version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.10
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=sample_deployment_ct' >> $BASH_ENV 
            virtualenv demo
            . demo/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . demo/bin/activate
            python demo_test.py
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            . demo/bin/activate
            docker build -t premvilas30/$IMAGE_NAME:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push premvilas30/$IMAGE_NAME
